server:
  port: 8080
spring:
  application:
    name: reference
  profiles:
    active: ${APP_PROFILE}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

